steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  env: ['DATABASE_NAME=recipease','JDBC_PASSWORD=recipease','JDBC_SCHEMA=recipease','JDBC_URL=34.70.51.191','JDBC_USERNAME=postgres']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/project2-251819/recipease', '.']
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - 'run'
  - '--image=gcr.io/project2-251819/recipease'
  - '--location=us-central1-a'
  - '--cluster=recipease-cluster'
images: ['gcr.io/project2-251819/recipease']
