steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  env: ['DATABASE_NAME=recipease','JDBC_PASSWORD=abc','JDBC_SCHEMA=recipease','JDBC_URL=34.70.51.191','JDBC_USERNAME=abc']
  args: ['echo','${JDBC_PASSWORD}']
- name: 'gcr.io/cloud-builders/docker'
  env: ['username=abc','password=123']
  env:
  - 'JDBC_PASSWORD=abc'
  args: ['build', '--tag=gcr.io/project2-251819/recipease --build-arg JDBC_PASSWORD=$$JDBC_PASSWORD', '.']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - 'run'
  - '--image=gcr.io/project2-251819/recipease'
  - '--location=us-central1-c'
  - '--cluster=hello-java-cluster'
  - '--expose=8080'
timeout: "1600s"
images: ['gcr.io/project2-251819/recipease']
options:
  env: ['DATABASE_NAME=recipease','JDBC_PASSWORD=abc','JDBC_SCHEMA=recipease','JDBC_URL=34.70.51.191','JDBC_USERNAME=abc']
  
