steps:
# installing the artifact:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  secretEnv:
  - 'JDBC_PASSWORD'
  
# building the docker image:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build -t gcr.io/project2-251819/recipease -f ./Dockerfile --build-arg JDBC_PASSWORD=$$JDBC_PASSWORD .']
  secretEnv: ['JDBC_PASSWORD'] 
  
# getting access to write to bucket:
#- name: 'gcr.io/cloud-builders/gsutil'
#  args: ['acl', 'ch', '-u', 'container-uploader@project2-251819.iam.gserviceaccount.com:W', 'gs://credentials-recipease']
  
# moving the build to bucket:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '-r', './target', 'gs://credentials-recipease/dr_recipease']
  
# move data to bucket:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['sql', 'export', 'sql', 'recipease-sql', 'gs://credentials-recipease/sqldumpfile.gz', '--database=recipease']
  
#- name: "gcr.io/cloud-builders/gcloud"
 # args: ["app", "deploy"]
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - 'run'
  - '--image=gcr.io/project2-251819/recipease'
  - '--location=us-central1-c'
  - '--cluster=hello-java-cluster'
  - '--expose=8080'
timeout: "1600s"
images: ['gcr.io/project2-251819/recipease']

# secrets:
secrets:
- kmsKeyName: 'projects/project2-251819/locations/global/keyRings/database/cryptoKeys/key'
  secretEnv:
    JDBC_PASSWORD: 'CiQAfvjyw1RzjLHoeUW93k/8iJV9iYnZXD4GqsIYvc2Mc8js1rgSIQBN1LoZmYCPQIAbKc1JEgWO/F09Gwl4lFcm+3SoD9bsmQ=='
    
