steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  secretEnv:
  - 'JDBC_PASSWORD'
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build -t gcr.io/$PROJECT_ID/go-fund-you:testlatest -f ./devops/Dockerfile --build-arg JDBC_PASSWORD=$$JDBC_PASSWORD .']
  secretEnv: ['JDBC_PASSWORD']
 
#- name: "gcr.io/cloud-builders/gcloud"
 # args: ["app", "deploy"]
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  args:
  - 'run'
  - '--image=gcr.io/project2-251819/recipease'
  - '--location=us-central1-c'
  - '--cluster=hello-java-cluster'
  - '--expose=8080'
timeout: "1600s"
images: ['gcr.io/project2-251819/recipease']

secrets:
- kmsKeyName: 'projects/project-2-251819/locations/global/keyRings/db_keyring/cryptoKeys/db_key'
  secretEnv:
    JDBC_PASSWORD: 'CiQAXCcwxxrLxGODpIM1ACEY6UuwYiBfXvD7agmQhWdbuXzgtkQSLAAQAZBN41rxrWOztit4SamJq/5FLtgd1x9Phm7Y4ygLJJL6txBaSNYH6mcw'
    
