language: java
sudo: true
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
after_success:
#  - docker build -t gcr.io/project2-251819/github.com/1907cloudgcp/recipeasev1:0.0.1 .
  - docker-credential-gcr configure-docker
  - gsutil cp gs://sub_demi_bog_entity_image_1/jsonkey2.json e.json
#  - openssl enc -d -aes-256-cbc -in encrypted.data -out e.json -k password
  - gcloud auth activate-service-account --key-file e.json
#  - cat aaa.json
  - docker build -t image .
  - docker tag image gcr.io/project2-251819/github.com/image
  - gcloud docker -- push gcr.io/project2-251819/github.com/image
  - y | gcloud app deploy --project project2-251819
  - gcloud config set compute/zone us-central1-a
  - # comment out later
  - gcloud container clusters create app1
  - gcloud container clusters get-credentials
  - kubectl delete service app1
  - kubectl create deployment hello-server --image=gcr.io/project2-251819/github.com/image@sha256:c8093b2b7dd3f72e50f6967d4f17677dcd1ba79c81d0ed3be0736092dd00acad
  - kubectl expose deployment hello-server --type LoadBalancer --port 80 --target-port 8080

before_install:
- chmod +x mvnw
- sudo apt-get install google-cloud-sdk
#- source /usr/lib/google-cloud-sdk/bin/gcloud
#- gcloud components install kubectl
#- /usr/lib/google-cloud-sdk/bin/gcloud components install kubectl
#- sudo apt-get install kubectl

- sudo apt-get update
- sudo apt-get install -y kubectl

- openssl aes-256-cbc -K ${encrypted_58f7fa4b7881_key} -iv ${encrypted_58f7fa4b7881_iv}
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
