language: java
sudo: true
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
after_success:
#  - docker build -t gcr.io/project2-251819/github.com/1907cloudgcp/recipeasev1:0.0.1 .
  - docker-credential-gcr configure-docker
  - gcloud auth activate-service-account --key-file ${JSON_key_file}
  - docker build -t image .
  - docker tag image gcr.io/project2-251819/github.com/image
  - gcloud docker -- push gcr.io/project2-251819/github.com/image

before_install:
- chmod +x mvnw
- sudo apt-get install google-cloud-sdk
- openssl aes-256-cbc -K ${encrypted_58f7fa4b7881_key} -iv ${encrypted_58f7fa4b7881_iv}
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
