language: java
sudo: true
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
after_success:
#  - docker build -t gcr.io/project2-251819/github.com/1907cloudgcp/recipeasev1:0.0.1 .
  - docker-credential-gcr configure-docker
  - gsutil cp gs://sub_demi_bog_entity_image_1/jsonkey2.json e.json
#  - openssl enc -d -aes-256-cbc -in encrypted.data -out e.json -k password
  - gcloud auth activate-service-account --key-file e.json
#  - cat aaa.json
  - docker build -t image .
  - docker tag image gcr.io/project2-251819/github.com/image
  - gcloud docker -- push gcr.io/project2-251819/github.com/image
  - y | gcloud app deploy --project project2-251819
  - gcloud config set compute/zone us-central1-a
  - # comment out later
  #This is just commenting on the current travis.yaml to diagnose the error, once we have succesful deployment, we proceed.
  #everything below this comment fails when building on travis. Probable issue is that since we failed to create the cluster for app1, the rest
  #tumbles down. Will write the travis error under each line. 
  - gcloud container clusters create app1
  #ERROR: (gcloud.container.clusters.create) ResponseError: code=403, message=Required "container.clusters.create" permission(s) for "projects/travis-ci-prod-2". See https://cloud.google.com/kubernetes-engine/docs/troubleshooting#gke_service_account_deleted for more info.
  - gcloud container clusters get-credentials
  - kubectl delete service app1  #Why does this kubectl deletes a service that doesnt exist? 
  - kubectl create deployment app1 --image=gcr.io/project2-251819/github.com/image@sha256:c8093b2b7dd3f72e50f6967d4f17677dcd1ba79c81d0ed3be0736092dd00acad
  - kubectl expose deployment app1 --type LoadBalancer --port 80 --target-port 8080

before_install:
- chmod +x mvnw
- sudo apt-get install google-cloud-sdk
#- source /usr/lib/google-cloud-sdk/bin/gcloud
#- gcloud components install kubectl
#- /usr/lib/google-cloud-sdk/bin/gcloud components install kubectl
#- sudo apt-get install kubectl

- sudo apt-get update
- sudo curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
- sudo chmod +x ./kubectl
- sudo mv ./kubectl /usr/local/bin/kubectl
#- sudo apt-get install -y kubectl

- openssl aes-256-cbc -K ${encrypted_58f7fa4b7881_key} -iv ${encrypted_58f7fa4b7881_iv}
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
