server:
  port: 8080

spring:
  application:
    name: recipease
  
  datasource:
    driverClassName: org.postgresql.Driver
    initilization-mode: never
    password: abc
    username: abc
    url: jdbc:postgresql://34.69.143.27:5432/postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: recipease
    show-sql: false
