server:
  port: 8080

spring:
  application:
    name: recipease
  
  datasource:
    dirverClassName: org.postgresql.Driver
    initilization-mode: never
    password: postgres
    username: postgres
    url: jdbc:postgresql://35.202.206.103:5432/postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: postgres
    show-sql: false
